/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TunersIndexRouteImport } from './routes/tuners/index'
import { Route as TunersIdRouteImport } from './routes/tuners/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TunersIndexRoute = TunersIndexRouteImport.update({
  id: '/tuners/',
  path: '/tuners/',
  getParentRoute: () => rootRouteImport,
} as any)
const TunersIdRoute = TunersIdRouteImport.update({
  id: '/tuners/$id',
  path: '/tuners/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tuners/$id': typeof TunersIdRoute
  '/tuners/': typeof TunersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tuners/$id': typeof TunersIdRoute
  '/tuners': typeof TunersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tuners/$id': typeof TunersIdRoute
  '/tuners/': typeof TunersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/tuners/$id' | '/tuners/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tuners/$id' | '/tuners'
  id: '__root__' | '/' | '/tuners/$id' | '/tuners/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TunersIdRoute: typeof TunersIdRoute
  TunersIndexRoute: typeof TunersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tuners/': {
      id: '/tuners/'
      path: '/tuners'
      fullPath: '/tuners/'
      preLoaderRoute: typeof TunersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tuners/$id': {
      id: '/tuners/$id'
      path: '/tuners/$id'
      fullPath: '/tuners/$id'
      preLoaderRoute: typeof TunersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TunersIdRoute: TunersIdRoute,
  TunersIndexRoute: TunersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
